#!/usr/bin/env python
"""Pick a FFN Edit erase count from an exact-leakage sweep.

Input: CSV generated by ``run_ffn_edit_exact_sweep_model.sh``.
Output: a small shell env file and JSON summary with the selected count.
Impact: read-only over metrics; does not touch checkpoints or datasets.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Pick calibrated FFN Edit count from exact sweep CSV.")
    parser.add_argument("--sweep-csv", type=Path, required=True)
    parser.add_argument("--target-relative-drop", type=float, required=True)
    parser.add_argument("--max-relative-drop", type=float, default=None)
    parser.add_argument("--output-env", type=Path, required=True)
    parser.add_argument("--output-json", type=Path, required=True)
    return parser.parse_args()


def to_float(value: str | None) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except ValueError:
        return None


def to_int(value: str | None) -> int | None:
    if value is None or value == "":
        return None
    try:
        return int(float(value))
    except ValueError:
        return None


def load_rows(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    parsed_rows: list[dict[str, Any]] = []
    for row in rows:
        count = to_int(row.get("ffn_edit_erase_num"))
        exact = to_float(row.get("exact_leakage_rate"))
        relative_drop = to_float(row.get("relative_exact_drop"))
        if count is None or count <= 0 or exact is None or relative_drop is None:
            continue
        parsed_rows.append(
            {
                "dataset_kind": row.get("dataset_kind"),
                "model_kind": row.get("model_kind"),
                "ffn_edit_erase_num": count,
                "exact_leakage_rate": exact,
                "contains_leakage_rate": to_float(row.get("contains_leakage_rate")),
                "baseline_exact_leakage_rate": to_float(row.get("baseline_exact_leakage_rate")),
                "absolute_exact_drop": to_float(row.get("absolute_exact_drop")),
                "relative_exact_drop": relative_drop,
                "metrics_json": row.get("metrics_json"),
            }
        )
    return parsed_rows


def choose_row(rows: list[dict[str, Any]], target_relative_drop: float, max_relative_drop: float | None):
    if not rows:
        raise SystemExit("no usable sweep rows")
    eligible = rows
    if max_relative_drop is not None:
        capped = [row for row in rows if row["relative_exact_drop"] <= max_relative_drop]
        if capped:
            eligible = capped
    return min(
        eligible,
        key=lambda row: (
            abs(row["relative_exact_drop"] - target_relative_drop),
            row["relative_exact_drop"] > target_relative_drop,
            row["ffn_edit_erase_num"],
        ),
    )


def main() -> None:
    args = parse_args()
    rows = load_rows(args.sweep_csv)
    selected = choose_row(rows, args.target_relative_drop, args.max_relative_drop)
    payload = {
        "sweep_csv": str(args.sweep_csv),
        "target_relative_drop": args.target_relative_drop,
        "max_relative_drop": args.max_relative_drop,
        "selected": selected,
        "candidates": rows,
    }
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    args.output_env.parent.mkdir(parents=True, exist_ok=True)
    args.output_env.write_text(
        "\n".join(
            [
                f"export FFN_EDIT_ERASE_NUM={selected['ffn_edit_erase_num']}",
                f"export PICKED_RELATIVE_EXACT_DROP={selected['relative_exact_drop']}",
                f"export PICKED_EXACT_LEAKAGE_RATE={selected['exact_leakage_rate']}",
                f"export PICKED_SWEEP_JSON='{args.output_json}'",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    print(json.dumps(payload, ensure_ascii=False, indent=2), flush=True)


if __name__ == "__main__":
    main()
